from pathlib import Path

path = Path('/home/ubuntu/mealora-foods/client/src/pages/Home.tsx')
text = path.read_text()
text = text.replace('const { user, isAuthenticated } = useAuth();', 'const { user, isAuthenticated, logout } = useAuth();')
text = text.replace('const [profileOpen, setProfileOpen] = useState(false);', 'const [profileOpen, setProfileOpen] = useState(false);\n  const [mobileNavOpen, setMobileNavOpen] = useState(false);')
old = '<header className="market-header"><button className="market-brand" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="brand-orbit"><Globe2 size={17} /></span><span>MEALORA<small>FOODS</small></span></button><nav className="market-nav"><button onClick={() => document.getElementById("cities")?.scrollIntoView({ behavior: "smooth" })}>Discover</button><button onClick={() => document.getElementById("tracking")?.scrollIntoView({ behavior: "smooth" })}>Track an order</button><a href="/partners">For partners</a></nav><div className="market-actions"><button className="delivery-location" onClick={setDeliveryLocation}><MapPin size={14} />{location}<ChevronDown size={13} /></button>{isAuthenticated ? <button className="profile-chip" onClick={() => setProfileOpen(!profileOpen)}><span>{user?.name?.slice(0, 1).toUpperCase() ?? "M"}</span>{user?.name?.split(" ")[0] ?? "Profile"}</button> : <button className="login-button" onClick={() => startLogin()}>Log in</button>}<button className="bag-button" onClick={() => setProfileOpen(!profileOpen)}><ShoppingBag size={17} /><b>{cartCount}</b></button><button className="mobile-menu" onClick={() => toast("Use the links above", { description: "The full navigation is available on wider screens." })}><Menu size={20} /></button></div></header>'
new = '<header className="market-header"><button className="market-brand" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="brand-orbit"><Globe2 size={17} /></span><span>MEALORA<small>FOODS</small></span></button><nav className="market-nav"><button onClick={() => document.getElementById("cities")?.scrollIntoView({ behavior: "smooth" })}>Discover</button><button onClick={() => document.getElementById("tracking")?.scrollIntoView({ behavior: "smooth" })}>Track an order</button><a href="/partners">For partners</a></nav><div className="market-actions"><button className="delivery-location" onClick={setDeliveryLocation}><MapPin size={14} />{location}<ChevronDown size={13} /></button>{isAuthenticated ? <button className="profile-chip" onClick={() => setProfileOpen(!profileOpen)}><span>{user?.name?.slice(0, 1).toUpperCase() ?? "M"}</span>{user?.name?.split(" ")[0] ?? "Profile"}</button> : <button className="login-button" onClick={() => startLogin()}>Log in</button>}<button className="bag-button" onClick={() => setProfileOpen(!profileOpen)}><ShoppingBag size={17} /><b>{cartCount}</b></button><button className="mobile-menu" aria-label="Open navigation" onClick={() => setMobileNavOpen(true)}><Menu size={20} /></button></div></header>'
if old not in text:
    raise SystemExit('header pattern not found')
text = text.replace(old, new)
old_profile = '{profileOpen && <div className="profile-popover"><div className="profile-popover-head"><div className="profile-avatar">{user?.name?.slice(0, 1).toUpperCase() ?? "M"}</div><div><strong>{user?.name ?? "Your Mealora account"}</strong><small>{user?.email ?? "Sign in to unlock orders and saved places"}</small></div></div><a href="/profile">Open profile & order history <ArrowRight size={14} /></a><button onClick={() => setProfileOpen(false)}>Close</button></div>}'
new_profile = '{profileOpen && <><button className="soft-backdrop" aria-label="Close account menu" onClick={() => setProfileOpen(false)} /><div className="profile-popover"><div className="profile-popover-head"><div className="profile-avatar">{user?.name?.slice(0, 1).toUpperCase() ?? "M"}</div><div><strong>{user?.name ?? "Your Mealora account"}</strong><small>{user?.email ?? "Sign in to unlock orders and saved places"}</small></div></div>{isAuthenticated ? <><a href="/profile">Open profile & order history <ArrowRight size={14} /></a><button onClick={() => void logout().then(() => { setProfileOpen(false); toast.success("You are logged out"); }).catch(() => toast.error("Could not log out"))}>Log out</button></> : <button onClick={() => startLogin()}>Log in to unlock orders</button>}<button onClick={() => setProfileOpen(false)}>Close</button></div></>}'
if old_profile not in text:
    raise SystemExit('profile pattern not found')
text = text.replace(old_profile, new_profile)
anchor = '<main>\n'
drawer = '<>{mobileNavOpen && <><button className="nav-backdrop" aria-label="Close navigation" onClick={() => setMobileNavOpen(false)} /><aside className="mobile-drawer" aria-label="Mobile navigation"><div className="mobile-drawer-head"><span>MEALORA <em>UGANDA</em></span><button aria-label="Close navigation" onClick={() => setMobileNavOpen(false)}><X size={19} /></button></div><button onClick={() => { setMobileNavOpen(false); document.getElementById("cities")?.scrollIntoView({ behavior: "smooth" }); }}>Discover places <ArrowRight size={16} /></button><button onClick={() => { setMobileNavOpen(false); document.getElementById("tracking")?.scrollIntoView({ behavior: "smooth" }); }}>Track an order <ArrowRight size={16} /></button><a href="/partners" onClick={() => setMobileNavOpen(false)}>For partners <ArrowRight size={16} /></a><div className="mobile-drawer-account">{isAuthenticated ? <><span>Signed in as {user?.name?.split(" ")[0] ?? "you"}</span><button onClick={() => void logout().then(() => { setMobileNavOpen(false); toast.success("You are logged out"); }).catch(() => toast.error("Could not log out"))}>Log out</button></> : <button onClick={() => { setMobileNavOpen(false); startLogin(); }}>Log in to Mealora <ArrowRight size={16} /></button>}</div></aside></>}</>\n\n    <main>\n'
if anchor not in text:
    raise SystemExit('main anchor not found')
text = text.replace(anchor, drawer, 1)
path.write_text(text)
